version: "3.8"
services:
  postgresql: 
    image: postgres
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: datadna
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5433:5432   
volumes:
  db:
    name: datadna